config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations', sessions: 'users/sessions' },
  path: '',
  path_names: {sign_in: 'login', sign_out: 'logout', edit: 'setting', sign_up: 'registration'}
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#delete'
  resources :users, only: [:show, :index] do
    resources :plans
    post '/create', to: 'plans#create'
  end
  get '/profile_edit', to: 'users#profile_edit'
  post '/profile_update', to: 'users#profile_update'
  get '/plans', to: 'plans#plan_index'
  resources :rooms, only: [:show, :index, :create]
  resources :plans do
    resources :requests, only: [:create, :edit]
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
end

app/models/user.rb
class User < ApplicationRecord
  scope :guides, -> { where(guide: false) }
  has_many :plans, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_plans, through: :likes, source: :plan
  has_many :comments
  has_many :from_messages, class_name: "Message",
          foreign_key: "from_id", dependent: :destroy
  has_many :to_messages, class_name: "Message",
          foreign_key: "to_id", dependent: :destroy
  has_many :sent_messages, through: :from_messages, source: :from
  has_many :received_messages, through: :to_messages, source: :to
  has_many :active_requests, class_name:  "Request",
                                  foreign_key: "tourist_id",
                                  dependent:   :destroy
  has_many :passive_requests, class_name:  "Request",
                                   foreign_key: "guide_id",
                                   dependent:   :destroy
  has_many :guides, through: :active_requests, source: :guide
  has_many :tourists, through: :passive_requests, source: :tourist

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable, :omniauthable, omniauth_providers: [:facebook]
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  validates :number, presence: true, length: { minimum: 9 }
  validates :university, presence: true, length: { minimum: 4 }
  validates :major, presence: true, length: { minimum: 4 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }, allow_nil: true
  mount_uploader :picture, PictureUploader
  mount_uploader :certification, PictureUploader
  validates :picture, presence: true

  # userがいなければfacebookアカウントでuserを作成するメソッド
  def self.from_omniauth(auth)
    user = User.where(email: auth.info.email).first
    if user
      return user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        # userモデルが持っているカラムをそれぞれ定義していく
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.name = auth.info.name
        user.image = auth.info.image
        user.uid = auth.uid
        user.provider = auth.provider

        # If you are using confirmable and the provider(s) you use validate emails,
        # uncomment the line below to skip the confirmation emails.
        user.skip_confirmation!
      end
    end
  end

  def remember_me
    true
  end

  # ユーザーが投稿に対して、すでにいいねをしているのかどうか
  def already_liked?(plan)
    self.likes.exists?(plan_id: plan.id)
  end

    # ガイドに申し込み
  # def apply(guide_user)
  #   self.guides << guide_user
  # end

  # ガイドへの申し込みキャンセルリクエスト
  # def cancel_request(guide_user)
  #   self.active_requests.find_by(guide_id: guide_user.id).destroy
  # end

  # ガイドに申し込んだことがあるかどうか
  # def applied?(guide_user)
  #   self.guides.include?(guide_user)
  # end

  # Send message to other user
  def send_message(other_user, room_id, content)
    from_messages.create!(to_id: other_user.id, room_id: room_id, content: content)
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  def new
    super
  end

  # POST /resource/confirmation
  def create
    super
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    super
  end

  protected

  # The path used after resending confirmation instructions.
  def after_resending_confirmation_instructions_path_for(resource_name)
    super(resource_name)
  end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    super(resource_name, resource)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < ApplicationController

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  def new
    super
  end

  # POST /resource/password
  def create
    super
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  protected

  def after_resetting_password_path_for(resource)
    super(resource)
  end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end
  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # def profile_edit
  # end
  #
  # def profile_update
  #   current_user.assign_attributes(account_update_params)
  #   if current_user.save
	#   redirect_to my_page_path, notice: 'プロフィールを更新しました'
  #   else
  #     render "profile_edit"
  #   end
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
    def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :guide])
    end

  # If you have extra params to permit, append them to the sanitizer.
    def configure_account_update_params
      devise_parameter_sanitizer.permit(:account_update, keys: [:picture, :university, :major, :hometown, :hobby, :detail ])
    end

  # The path used after sign up.
    def after_sign_up_path_for(resource)
      super(resource)
    end

    def update_resource(resource, params)
      resource.update_without_password(params)
    end

    def after_update_path_for(resource)
      edit_user_registration_path(resource)
    end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]
  after_action :set_session, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    # super do |resource|
    #   BackgroundWorker.trigger(resource)
    # end
    self.resource = warden.authenticate!(auth_options)
    set_flash_message(:notice, :signed_in) if is_navigational_format?
    sign_in(resource_name, resource)
    if !session[:return_to].blank?
      redirect_to session[:return_to]
      session[:return_to] = nil
    else
      respond_with resource, :location => after_sign_in_path_for(resource)
    end
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  private

    def set_session
      session[:user_id] = current_user&.id
    end

  protected

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || super
  end
  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [ :name, :email, :guide ])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def index
    # @users = User.all.reject { |user| user.guide }
    @users = User.guides.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  # def new
  #    @user = User.new
  # end
  #
  # def create
  #   @user = User.new(user_params)
  #   if @user.save
  #     log_in @user
  #     flash[:success] = "Welcome to the Sample App!"
  #     redirect_to @user
  #   else
  #     render 'new'
  #   end
  # end

  # def edit
  #   @user = current_user
  # end
  #
  # def update
  #   @user = current_user
  #   if @user.update_attributes(update_params)
  #     flash[:success] = "Profile updated"
  #     redirect_to @user
  #   else
  #     render 'edit'
  #   end
  # end

  def profile_edit
    @user = current_user
  end

  def profile_update
    @user = current_user
    if current_user.update_attributes(profile_params)
      redirect_to user_path(@user.id), notice: 'プロフィールを更新しました'
    else
      render "profile_edit"
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    def update_params
      params.require(:user).permit(:name, :number, :email)
    end

    def profile_params
      params.require(:user).permit(:name, :university, :major, :hometown, :hobby, :detail, :picture)
    end
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_user.html.erb
<div class="col-6 col-md-4 mt-4">
  <div class="card" style="width: 18rem;">
    <%= link_to image_tag(user.picture, class: "card-img-top",
          height: "241.5", alt: "サンプル画像"), user_path(user.id) %>
    <div class="card-body">
      <h5 class="card-title"><%= user.name %><%= link_to "more detail", user_path(user.id), class:"float-right btn btn-sm btn-primary" %></h5>
      <p class="card-text">univ: <%= user.university %></p>
    </div>
  </div>
  <div class="m-4">
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1 class="font-italic my-5">All Guides</h1>

<%= will_paginate(@users, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>

<ul class="users">
  <div class="row">
    <% @users.each do |user| %>
      <%= render user %>
    <% end %>
  </div>
</ul>

<%= will_paginate(@users, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
   <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/profile_edit.html.erb
<div class="container mt-5 mb-5">
  <%= form_for current_user, url: {action: 'profile_update'}, method: :post do |f| %>
  <div class="row">
    <div class="col-md-6">
      <%= image_tag @user.picture.url, class: "mx-auto d-block w-auto h-auto" %>
      <div class="field">
        <%= f.file_field :picture, class: "mb-3 mt-3 w-75 mx-auto d-block",
                  autofocus: true, autocomplete: "picture" %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="field row">
        <%= f.label :name, class: "mr-4 col-sm-2 font-italic" %>/
        <div class="col-sm-6">
          <nobr>
            <%= f.text_field :name, class: "mb-2", autofocus: true, autocomplete: "name" %>
          </nobr>
        </div>
      </div>

      <div class="field row">
        <%= f.label :university, class: "mr-4 col-sm-2 font-italic" %>/
        <div class="col-sm-6">
          <nobr>
            <%= f.text_field :university, autofocus: true, autocomplete: "university" %>
          </nobr>
        </div>
      </div>

      <div class="field row">
        <%= f.label :major, class: "mr-4 col-sm-2 font-italic" %>/
        <div class="col-sm-6">
          <nobr>
            <%= f.text_field :major, autofocus: true, autocomplete: "major" %>
          </nobr>
        </div>
      </div>

      <div class="field row">
        <%= f.label :hometown, class: "mr-4 col-sm-2 font-italic" %>/
        <div class="col-sm-6">
          <nobr>
            <%= f.text_field :hometown, autofocus: true, autocomplete: "hometown" %>
          </nobr>
        </div>
      </div>

      <div class="field row">
        <%= f.label :hobby, class: "mr-4 col-sm-2 font-italic" %>/
        <div class="col-sm-6">
          <nobr>
            <%= f.text_field :hobby, autofocus: true, autocomplete: "hobby" %>
          </nobr>
        </div>
      </div>

      <div class="field row">
        <%= f.label :detail, class: "mr-4 col-sm-2 font-italic" %>/
        <div class="col-sm-8">
          <%= f.text_area :detail, class: "h-100", autofocus: true, autocomplete: "detail" %>
        </div>
      </div>

      <div class="actions">
        <div class="row justify-content-center">
            <%= f.submit "edit", class: "w-50 btn btn-sm btn-primary rounded-pill mt-5 ml-5",
                      data: { confirm: "You sure?" } %>
        </div>
      </div>

    </div>
  </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container mt-5 mb-5">
  <div class="row">
    <div class="col-md-6">
      <%= image_tag @user.picture.url, class: "h-auto w-auto d-block mx-auto" %>
    </div>

    <div class="col-md-6">
      <div class="row field">
        <label class="mr-4 col-sm-2 font-italic">Name</label>/
        <div class="col-sm-5">
          <nobr>
            <span class="mb-2"><%= @user.name %></span>
          </nobr>
        </div>
      </div>

      <div class="row field">
        <label class="mr-4 col-sm-2 font-italic">University</label>/
        <div class="col-sm-5">
          <nobr>
            <span class="mb-2"><%= @user.university %></span>
          </nobr>
        </div>
      </div>

      <div class="row field">
        <label class="mr-4 col-sm-2 font-italic">Major</label>/
        <div class="col-sm-5">
          <nobr>
            <span class="mb-2"><%= @user.major %></span>
          </nobr>
        </div>
      </div>

      <div class="row field">
        <label class="mr-4 col-sm-2 font-italic">Hometown</label>/
        <div class="col-sm-5">
          <nobr>
            <span class="mb-2"><%= @user.hometown %></span>
          </nobr>
        </div>
      </div>

      <div class="row filed">
        <label class="mr-4 col-sm-2 font-italic">Hobby</label>/
        <div class="col-sm-5">
          <nobr>
            <span class="mb-2"><%= @user.hobby %></span>
          </nobr>
        </div>
      </div>

      <div class="row field">
        <label class="mr-4 col-sm-2 font-italic">Detail</label>/
        <div class="col-sm-8">
          <span class="mb-2 word-break"><%= @user.detail %></span>
        </div>
      </div>

      <div class="actions">
        <div class="row justify-content-center">
          <% if @user == current_user %>
            <%= link_to "to edit page", profile_edit_path,
              class: "w-50 btn btn-sm btn-primary rounded-pill mt-5 ml-5" %>
          <% end %>
        </div>
      </div>

    </div>
  </div>
<div class="dropdown-divider"></div>
<h4 class="font-italic mt-5 mb-5 text-center">Like Plans</h4>
<ul class="plans">
  <div class="row">
  <% @user.liked_plans.each do |plan| %>
  <div class="col-6 col-md-4 mt-4">
    <div class="card">
      <%= link_to image_tag(plan.image, class: "card-img-top", height: "241.5", alt: "サンプル画像"),
          user_plan_path(plan.user_id, plan.id) %>
      <div class="card-body">
      <div class="card-title"><%= plan.name %><%= link_to "more detail", user_plan_path(plan.user_id, plan.id),
          class:"float-right btn btn-sm btn-primary mt-n1" %></div>
      <div class="card-text">
        <div class="row">
          <div class="col-md-7">
            <%= plan.tag %>
          </div>
          <div class="col-md-5">
            <% if current_user&.id == plan.user.id %>
              <%= link_to 'Edit', edit_user_plan_path(@user.id, plan.id) %>
              <%= link_to 'Destroy', user_plan_path(@user.id, plan.id), method: :delete,
              data: { confirm: 'Are you sure?' } %>
            <% end %>
          </div>
        </div>
      </div>
      </div>
    </div>
  </div>
  <% end %>
  </div>
</ul>
</div>