config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations', sessions: 'users/sessions' },
  path: '',
  path_names: {sign_in: 'login', sign_out: 'logout', edit: 'setting', sign_up: 'registration'}
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#delete'
  resources :users, only: [:show, :index] do
    resources :plans
    post '/create', to: 'plans#create'
  end
  get '/profile_edit', to: 'users#profile_edit'
  post '/profile_update', to: 'users#profile_update'
  get '/plans', to: 'plans#plan_index'
  resources :rooms, only: [:show, :index, :create]
  resources :plans do
    resources :requests, only: [:create, :edit]
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
end

app/models/plan.rb
class Plan < ApplicationRecord
  mount_uploader :image, PictureUploader
  belongs_to :user
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
  has_many :comments
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :name, presence: true, length: { maximum: 40 }
  validates :tag, presence: true
  validates :content, presence: true, length: { maximum: 1000 }
  validates :image, presence: true

  def self.search(search) #ここでのself.はPlan.を意味する
    plans = self.all

    if search[:kwd].present?
      plans = plans.where(['name LIKE ? OR content LIKE ? ', "%#{search[:kwd]}%", "%#{search[:kwd]}%"]) # 検索とnameの部分一致を表示。
    end
    if search[:tag].present?
      plans = plans.where(['tag LIKE ? ', "#{search[:tag]}%"])
    end
    return plans
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :authenticate_user!, only: [:new, :show, :edit, :destroy, :create, :update]

  def index
    @user = User.find(params[:user_id])
    @plans = @user.plans.all
  end

  def plan_index
    @user = current_user
    if params[:search].present?
      @plans = Plan.search(params[:search]).paginate(page: params[:page])
    else
      @plans = Plan.paginate(page: params[:page])
    end
  end

  def show
    @user = User.find(params[:user_id])
    @plan = @user.plans.find(params[:id])
    @like = Like.new
    @comments = @plan.comments
    @comment = Comment.new
  end

  def new
    @user = User.find(params[:user_id])
    @plan = @user.plans.build
  end

  def edit
    @user = User.find(params[:user_id])
    @plan = @user.plans.find(params[:id])
  end

  def destroy
    @user = User.find(params[:user_id])
    @plan = @user.plans.find(params[:id])
    @plan.destroy
    redirect_to plans_path, notice: "The plan was destoyed successfully"
  end

  def create
    @user = User.find(params[:user_id])
    @plan = @user.plans.build(plan_params)
    if @plan.save
      redirect_to plans_path, notice: "The new plan was created"
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:user_id])
    @plan = @user.plans.find_by(id: params[:id])
    if @plan.update_attributes(plan_params)
      redirect_to plans_path, notice: "Plan was edited successfully"
    else
      render 'edit'
    end
  end

  private

    def plan_params
      params.require(:plan).permit(:content, :name, :tag, :image)
    end

end

app/helpers/plans_helper.rb
module PlansHelper

  def search_params(filter)
    if params[:search].present?
      return params[:search][filter.to_sym]
    else
      return ""
    end
  end
end

app/views/plans/_plan.html.erb
<li id="plan"<%= plan.id %>">
  <%= link_to gravatar_for(plan.user, size: 50), plan.user %>
  <span class="user"><%= link_to plan.user.name, plan.user %></span>
  <span class="content"><%= plan.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(plan.created_at) %> ago.
  </span>
</li>

app/views/plans/edit.html.erb
<%= form_for(@plan, url: user_plan_path(@user.id, @plan.id)) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
<div class="row my-5">
  <div class="col-6">
    <div class="mt-3 mb-3">
      <%= image_tag @plan.image, class: "mx-auto d-block", height: "250", alt: "サンプル画像" %>
    </div>
      <%= f.file_field :image , class:"mt-3 ml-5 w-75" %>
    <div style="height:280px;" class="rounded-circle col-7 ml-5 mt-5">
      <%= image_tag @user.picture, class: "plan-img mx-auto d-block rounded-circle mt-4", width: "250", height: "250", alt: "サンプル画像" %>
    </div>
  </div>
  <div style="height:500px;" class="col-6 border border-secondary mt-3">
    <p>The name of plan<p>
      <%= f.text_field :name, class:"h-10 col-6 center", placeholder: "ex) Let's go to Asakusa" %>
    <p>Plan detail</p>
      <%= f.text_area :content, rows: "10", cols: "20", class:"h-50"%>
    <div class="input-group mb-3 mt-3">
      <div class="input-group-prepend">
        <label class="input-group-text" for="inputGroupSelect01">ジャンル</label>
      </div>
     <%= f.select :tag, [["Food&Drink", "Food&Drink"], ["Alchol", "Alchol"],
      ["Event", "Event"], ["Activity", "Activity"], ["Trend", "Trend"], ["Secret Spot", "Secret Spot"],
      ["Shopping", "Shopping"], ["School", "School"], ["Kawaii", "Kawaii"]] ,class:"form-control" %>
    </div>
    <%= f.submit "Edit the plan", class: "btn btn-lg btn-primary rounded-pill mt-5" %>
  </div>
</div>
<% end %>

app/views/plans/index.html.erb
<% provide(:title, @user.name) %>
<div class="row">
<% @plans.each do |plan| %>
  <div class="col-6 col-md-4 mt-4 ">
    <div class="card">
      <%= image_tag(plan.image, class: "card-img-top", alt: "サンプル画像") %>
      <div class="card-body">
        <div class="card-title"><%= plan.name%></div>
        <div class="card-text">
          <%= link_to 'Edit', edit_user_plan_path(@user.id, plan.id) %>
          <%= link_to 'Destroy', user_plan_path(@user.id, plan.id), method: :delete,
                                       data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    </div>
    <!-- <div class="m-4">
        <%= link_to 'Edit', edit_user_plan_path(@user.id, plan.id) %>
        <%= link_to 'Destroy', user_plan_path(@user.id, plan.id), method: :delete,
                                     data: { confirm: 'Are you sure?' } %>
    </div> -->
  </div>
<% end %>
</div>

app/views/plans/new.html.erb
<%= form_for(@plan, url: user_plans_path) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<div class="row mt-5 mb-5">
  <div class="col-6">
    <div style="height:250px;", class="mx-auto col-8 border border-secondary mt-3 mb-3">
      <p>Plan's image</p>
    </div>
      <div class="field">
        <%= f.file_field :image , class:"mt-3 mb-5 ml-5 w-75" %>
      </div>
    <div>
      <p><%= @user.name %>'s image</p>
      <%= image_tag @user.picture, width: "250", height: "250",
          class: "plan-img mx-auto d-block rounded-circle", alt: "サンプル画像" %>
    </div>
  </div>

  <div style="height:500px;" class="col-6 border border-secondary mt-3 mb-3">
    <p>The name of plan<p>
      <%= f.text_field :name , class:"h-10 col-6 center", :placeholder =>"ex) Let's go to Asakusa"%>
    <p>Plan detail</p>
      <%= f.text_area :content, rows: "10", cols: "20", class:"h-50", :placeholder =>"ex) Im going to take you to Asakusa. Here is the one of the most famous place for foreigner in Japan."%>
    <div class="input-group mb-3 mt-3">
      <div class="input-group-prepend">
        <label class="input-group-text" for="inputGroupSelect01">ジャンル</label>
      </div>
      <%= f.select :tag, [["Food&Drink", "Food&Drink"], ["Alchol", "Alchol"],
      ["Event", "Event"], ["Activity", "Activity"], ["Trend", "Trend"], ["Secret Spot", "Secret Spot"],
      ["Shopping", "Shopping"], ["School", "School"], ["Kawaii", "Kawaii"]] ,class:"form-control" %>
    </div>
    <%= f.submit "Create the plan", class: "btn btn-lg btn-primary rounded-pill mt-5" %>
  </div>
</div>
<% end %>

app/views/plans/plan_index.html.erb
<% provide(:title, 'All plans') %>
<h1 class="font-italic my-5">All Plans</h1>
<%= will_paginate(@plans, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>

<!-- 検索拡張機能 -->
<div class="row mt-1">
  <div class="col-md-7 offset-md-4">
    <p>search plan</p>
    <%= form_for(:search, url: plans_path, method: 'get') do |f| %>
      <%= f.text_field :kwd, value: search_params("kwd"), class: "form-control-sm w-50 mr-3 mb-3" %>
      <div class="row">
        <div class="col-md-6">
          <%= f.select :tag, [["Food&Drink", "Food&Drink"], ["Alchol", "Alchol"],
          ["Event", "Event"], ["Activity", "Activity"], ["Trend", "Trend"], ["Secret Spot", "Secret Spot"],
          ["Shopping", "Shopping"], ["School", "School"], ["Kawaii", "Kawaii"]],
          include_blank: true, selected: search_params("tag"), class: "form-control-lg mr-3" %>
        </div>
        <div class="col-md-6">
          <%= f.submit 'Search', name: nil, class: "btn btn-sm btn-primary rounded-pill w-25" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<ul class="plans">
  <div class="row">
    <% @plans.each do |plan| %>
    <div class="col-6 col-md-4 mt-4">
      <div class="card">
        <%= link_to image_tag(plan.image, class: "card-img-top", height: "241.5", alt: "サンプル画像"),
            user_plan_path(plan.user_id, plan.id) %>
        <div class="card-body">
        <div class="card-title"><%= plan.name %><%= link_to "more detail", user_plan_path(plan.user_id, plan.id),
            class:"float-right btn btn-sm btn-primary mt-n1" %></div>
        <div class="card-text">
          <div class="row">
            <div class="col-md-7">
              <%= plan.tag %>
            </div>
            <div class="col-md-5">
              <% if current_user&.id == plan.user.id %>
                <%= link_to 'Edit', edit_user_plan_path(@user.id, plan.id) %>
                <%= link_to 'Destroy', user_plan_path(@user.id, plan.id), method: :delete,
                data: { confirm: 'Are you sure?' } %>
              <% end %>
            </div>
          </div>
        </div>
        </div>
      </div>
    </div>
   <% end %>
 </div>
</ul>

<%= will_paginate(@plans, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>

app/views/plans/show.html.erb
<% provide(:title, @user.name) %>
<div class="row mt-5 mb-5">
  <div class="col-md-6">
    <div class="field">
      <p>Plan's image</p>
      <%= image_tag @plan.image, class: "mx-auto d-block mt-3 mb-5 w-auto",
          height: "250", alt: "プラン画像" %>
    </div>
    <div>
      <p><%= @user.name %>'s image</p>
      <%= image_tag @user.picture, width: "250", height: "250",
          class: "plan-img mx-auto d-block rounded-circle", alt: "ユーザー画像" %>
    </div>
  </div>

  <div style="height:500px;" class="col-6 border border-secondary mt-3">
    <div class="row">
      <div class="col-md-10">
        <h5 class="mt-3 mb-3">The name of plan</h5>
      </div>
      <div class="col-md-2">
        <% if current_user&.already_liked?(@plan) %>
          Like!<%= link_to icon("fas", "star"),
              plan_like_path(@plan), method: :delete, class: "text-warning ml-2" %>
        <% else %>
          Like!<%= link_to icon("far", "star"),
              plan_likes_path(@plan), method: :post, class: "text-warning ml-2" %>
        <% end %>
      </div>
    </div>
    <div class="h-10 col-6 border border-secondary">
      <%= @plan.name %>
    </div>
    <h5 class="mt-3">Plan detail</h5>
    <p class="h-50 border border-secondary mt-3 word-break">
      <%= @plan.content %>
    </p>
    <h5 class="mt-3">The name of tag</h5>
    <div class="input-group mb-3 mt-3 border border-secondary">
      <%= @plan.tag %>
    </div>
      <% if current_user&.guide == true %>
        <%= link_to "Apply", plan_requests_path(@plan, guide_id: @plan.user.id), method: :post, data: { confirm: 'Are you sure?' },
            class: "mt-apply mx-auto d-block btn btn-lg btn-primary rounded-pill w-75" %>
      <% end %>
  </div>
</div>

<div class="dropdown-divider"></div>
<h4 class="text-center font-italic mt-5">Comments</h4>
<% @comments.each do |comment| %>
  <% if @user != comment.user %>
  <div class="row mb-3">
    <div class="col-md-1 offset-md-3 border-bottom">
      <%= link_to image_tag(comment.user.picture, width: "60", height: "60",
              class: "plan-img rounded-circle"), user_path(comment.user) %>
    </div>
    <div class="col-md-1 mt-3 border-bottom">
      <h5><%= link_to comment.user.name, user_path(comment.user) %></h5>
    </div>
    <div class="text-right col-md-3 mt-3 border-bottom">
      <small><%= comment.created_at.year %>.
        <%= comment.created_at.month %>/
        <%= comment.created_at.day %>
        <%= comment.created_at.hour %> :
        <%= comment.created_at.min %></small>
    </div>
  </div>
  <div class="row offset-md-4">
    <p><%= comment.review %></p>
  </div>
  <% else %>
  <div class="row mb-3">
    <div class="col-md-3 offset-md-3 mt-4 border-bottom">
      <small><%= comment.created_at.year %>.
        <%= comment.created_at.month %>/
        <%= comment.created_at.day %>
        <%= comment.created_at.hour %> :
        <%= comment.created_at.min %></small>
    </div>
    <div class="text-right col-md-2 mt-3 border-bottom">
      <%= link_to image_tag(comment.user.picture, width: "60", height: "60",
          class: "plan-img rounded-circle"), user_path(comment.user) %>
    </div>
  </div>
  <div class="row offset-md-4">
    <p><%= comment.review %></p>
  </div>
  <% end %>
<% end %>

<%= form_for([@plan, @comment]) do |f| %>
  <div class="row my-5">
    <div class="col-md-4 offset-md-3">
      <%= f.text_field :review, class: "form-control" %>
    </div>
    <div class="col-md-5">
      <%= f.submit "comment",
          class: "text-center btn btn-primary rounded-pill w-25" %>
    </div>
  </div>
<% end %>