config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations', sessions: 'users/sessions' },
  path: '',
  path_names: {sign_in: 'login', sign_out: 'logout', edit: 'setting', sign_up: 'registration'}
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#delete'
  resources :users, only: [:show, :index] do
    resources :plans
    post '/create', to: 'plans#create'
  end
  get '/profile_edit', to: 'users#profile_edit'
  post '/profile_update', to: 'users#profile_update'
  get '/plans', to: 'plans#plan_index'
  resources :rooms, only: [:show, :index, :create]
  resources :plans do
    resources :requests, only: [:create, :edit]
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
end

app/views/layouts/_footer.html.erb
<footer class='text-center card'>
  <div class="wrapper">
    <div class="row">
      <div class="col-md-4 col-sm-4">
        <ul class="nav flex-column mt-2">
          <li class="nav-item mt-2"><%= link_to '運営会社', '#', class: "nav-link" %></li>
          <li class="nav-item mt-1"><%= link_to 'ブログ', '#', class: "nav-link" %></li>
        </ul>
      </div>
      <div class="col-md-4 col-sm-4">
        <ul class="nav flex-column mt-2">
          <li class="nav-item mt-2"><%= link_to 'ヘルプ', help_path, class: "nav-link" %></li>
          <li class="nav-item mt-1"><%= link_to 'サイトマップ', '#', class: "nav-link" %></li>
        </ul>
      </div>
      <div class="col-md-4 col-sm-4">
        <ul class="nav flex-column mt-2">
          <li class="nav-item mt-2"><%= link_to '利用規約', '#', class: "nav-link" %></li>
          <li class="nav-item mt-1"><%= link_to 'プライバシーポリシー', '#', class: "nav-link" %></li>
          <li class="nav-item mt-1"><%= link_to '特定商取引', '#', class: "nav-link" %></li>
        </ul>
      </div>
    </div>
    <h7>© copyright 2019 PAM Inc. All Rights Reserved.</h7>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-light bg-light sticky-top">
  <div class="container">
    <%= link_to image_tag("PAM.png", alt: "PAM logo",
             width: '55', height: '50', class: "rounded-circle"), root_path %>
    <nav>
      <ul class="nav nav-tabs">
        <% if user_signed_in? & !current_user&.guide %>
          <li class="nav-item"><%= link_to "Make Plan", new_user_plan_path(current_user.id), class: "nav-link" %></li>
        <% end %>
        <li class="nav-item"><%= link_to "Plans", plans_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to "Guides", users_path, class: "nav-link" %></li>
        <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
            Chat with <b class="caret"></b>
          </a>
          <ul class="dropdown-menu chat-dropdown user-dropdown-menu">
            <% if current_user.guide %> <%# 旅行者のとき %>
              <% @requests = current_user.active_requests.where(approved: true) %>
            <% else %>  <%# ガイドのとき %>
              <% @requests = current_user.passive_requests.where(approved: true) %>
            <% end %>
            <% @requests.each do |request| %>
              <% if current_user.guide %> <%# 旅行者のとき %>
                <% user = request.guide %>
              <% else %> <%# ガイドのとき %>
                <% user = request.tourist %>
              <% end %>
              <li class="row mb-2 mx-sm-1">
                <div class="col-md-3">
                  <%= link_to image_tag(user.picture.url, width: "35", height: "35",
                      class: "chat-img rounded-circle"), room_path(user.id) %>
                </div>
                <div class="col-md-8 ml-2">
                  <h7><%= link_to user.name, room_path(user.id) %></h7>
                </div>
              </li>
            <% end %>
          </ul>
        </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_registration_path %></li>
              <li class="dropdown-divider"></li>
              <li class="nav-item"><%= link_to "Log out", logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to "Signup", new_user_registration_path, class: "nav-link"%></li>
          <li class="nav-item"><%= link_to "Login", login_path, class: "nav-link"%></li>
        <% end %>
      </ul>
    </nav>
    </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                           'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application',
                           'data-turbolinks-track': 'reload' %>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container mt-2">
      <% if notice %>
        <div class="alert alert-info alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
            <span class="sr-only">close</span>
          </button>
        <%= notice %>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
            <span class="sr-only">close</span>
          </button>
        <%= alert %>
        </div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/layouts/landing_page.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
      <% if notice %>
        <div class="alert alert-info alert-dismissible mb-n1" role="alert">
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
            <span class="sr-only">close</span>
          </button>
        <%= notice %>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger alert-dismissible mb-n1" role="alert">
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
            <span class="sr-only">close</span>
          </button>
        <%= alert %>
        </div>
      <% end %>
        <%= yield %>
        <%= render 'layouts/footer' %>
  </body>
</html>